server:
  port: 80
eureka:
  client:
     #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    register-with-eureka: true
    #是否从服务端抓取已有的注册信息
    fetch-registry: true
    service-url:
        #,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
spring:
  application:
    name: cloud-consumer-order