server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
#  zipkin:
#    base-url: http://localhost:9411
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#  sleuth:
#    sampler:
#      probability: 1 #采样率 1为全部采集


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lin.entities

eureka:
  client:
    #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    register-with-eureka: true
    #是否从服务端抓取已有的注册信息
    fetch-registry: true
    service-url:
      #,http://eureka7002.com:7002/eureka
      defaultZone: http://localhost:7001/eureka
